POST http://localhost:8080/candidate
Content-Type: application/json

{
    "username" : "Maria",
    "name" : "Maria de Sousa",
    "email" : "maria@gmail.com",
    "password" : "12345678910",
    "description" : "Desenvolvedora Java"
},

###

POST http://localhost:8080/company
Content-Type: application/json

{
    "username" : "Maria",
    "name" : "Maria de Sousa",
    "email" : "maria@gmail.com",
    "password" : "12345678910",
    "description" : "Desenvolvedora Java"
},
